### ISSUE TITLE
hubot error when typing hubot stock aapl

### ISSUE THREAD

**Issue by snazzybunny** [gyoza/hubot-stocks-googlesource#1]
Hello,

I'm getting these errors when trying to run hubot stock aapl. 

`[Tue Feb 06 2018 08:31:58 GMT-0500 (EST)] ERROR TypeError: Cannot read property 'on' of undefined
    at /home/andyph666/myhubot/node_modules/scoped-http-client/src/index.js:87:15
    at TextListener.callback (/home/andyph666/myhubot/scripts/stocks.coffee:28:5)
    at /home/andyph666/myhubot/node_modules/hubot/src/listener.coffee:65:12
    at allDone (/home/andyph666/myhubot/node_modules/hubot/src/middleware.coffee:44:37)
    at /home/andyph666/myhubot/node_modules/async/lib/async.js:274:13
    at Object.async.eachSeries (/home/andyph666/myhubot/node_modules/async/lib/async.js:142:20)
    at Object.async.reduce (/home/andyph666/myhubot/node_modules/async/lib/async.js:268:15)
    at /home/andyph666/myhubot/node_modules/hubot/src/middleware.coffee:49:13
    at process._tickCallback (internal/process/next_tick.js:150:11)
`
 
Does this coffee script still work or is the API outdated like a lot of the hubot-stock scripts. Running node v9.5.0 and npm v5.6.0. Thanks!

**Comment by gyoza** [comment]
new version coming soon, google and yahoo have basically told us to GTFO.  I have a working version without pretty graphs at this point.

**Comment by gyoza** [comment]
uploaded the one that just gives you prices.. no ticker yet.. I've yet to find a replacement for this particular feature.. So, if you know where i can easily get tickers via some sort of API i can include it.

**Comment by gyoza** [comment]
```
[6:11 AM] ᕕ( ՞ ᗜ ՞ )ᕗ: @j stock aapl
[6:11 AM] Jeeves Bot: Apple Inc. [AAPL] Nasdaq Global Select - Technology
[6:11 AM] Jeeves Bot: Real-time or Closing price: 155.69
[6:13 AM] ᕕ( ՞ ᗜ ՞ )ᕗ: @j stock tsla
[6:13 AM] Jeeves Bot: Tesla Inc. [TSLA] Nasdaq Global Select - Consumer Cyclical
[6:13 AM] Jeeves Bot: Real-time or Closing price: 333.13
```

**Comment by snazzybunny** [comment]
That's odd. This is what I'm getting. I think my brother knows where to get tickers easily with an API. Will get back to you on that. Thanks for the help! I replaced the script with the one you just uploaded. Am I missing dependencies or anything?

`[Tue Feb 06 2018 09:15:11 GMT-0500 (EST)] INFO [Incoming] snazzybunny: hubot stock aapl
[Tue Feb 06 2018 09:15:11 GMT-0500 (EST)] INFO Checking to see if method: getRoomNameById exists
[Tue Feb 06 2018 09:15:11 GMT-0500 (EST)] INFO Looking up Room Name for: GENERAL
[Tue Feb 06 2018 09:15:11 GMT-0500 (EST)] INFO setting roomName: general
[Tue Feb 06 2018 09:15:11 GMT-0500 (EST)] INFO Message sent to hubot brain.
[Tue Feb 06 2018 09:15:11 GMT-0500 (EST)] ERROR TypeError: Cannot read property 'on' of undefined
    at /home/andyph666/myhubot/node_modules/scoped-http-client/src/index.js:87:15
    at TextListener.callback (/home/andyph666/myhubot/scripts/stocks.coffee:32:5)
    at /home/andyph666/myhubot/node_modules/hubot/src/listener.coffee:65:12
    at allDone (/home/andyph666/myhubot/node_modules/hubot/src/middleware.coffee:44:37)
    at /home/andyph666/myhubot/node_modules/async/lib/async.js:274:13
    at Object.async.eachSeries (/home/andyph666/myhubot/node_modules/async/lib/async.js:142:20)
    at Object.async.reduce (/home/andyph666/myhubot/node_modules/async/lib/async.js:268:15)
    at /home/andyph666/myhubot/node_modules/hubot/src/middleware.coffee:49:13
    at process._tickCallback (internal/process/next_tick.js:150:11)`

**Comment by gyoza** [comment]
Mmmmmmmm I'll check my versions here in a few.. Making coffee ha

**Comment by gyoza** [comment]
Should be good now. I was editing on a file that was not being loaded... Lol... Its early...

**Comment by snazzybunny** [comment]
haha no worries. Must be a dependency issue then :o. I just tried it again right now with the code you just pushed. Made sure I rebooted the bot as well.

`[Tue Feb 06 2018 09:48:02 GMT-0500 (EST)] INFO [Incoming] snazzybunny: hubot stock tsla
[Tue Feb 06 2018 09:48:02 GMT-0500 (EST)] INFO Checking to see if method: getRoomNameById exists
[Tue Feb 06 2018 09:48:02 GMT-0500 (EST)] INFO Looking up Room Name for: GENERAL
[Tue Feb 06 2018 09:48:02 GMT-0500 (EST)] INFO setting roomName: general
[Tue Feb 06 2018 09:48:02 GMT-0500 (EST)] INFO Message sent to hubot brain.
[Tue Feb 06 2018 09:48:02 GMT-0500 (EST)] ERROR TypeError: Cannot read property 'on' of undefined
    at /home/andyph666/myhubot/node_modules/scoped-http-client/src/index.js:87:15
    at TextListener.callback (/home/andyph666/myhubot/scripts/stocks.coffee:32:5)
    at /home/andyph666/myhubot/node_modules/hubot/src/listener.coffee:65:12
    at allDone (/home/andyph666/myhubot/node_modules/hubot/src/middleware.coffee:44:37)
    at /home/andyph666/myhubot/node_modules/async/lib/async.js:274:13
    at Object.async.eachSeries (/home/andyph666/myhubot/node_modules/async/lib/async.js:142:20)
    at Object.async.reduce (/home/andyph666/myhubot/node_modules/async/lib/async.js:268:15)
    at /home/andyph666/myhubot/node_modules/hubot/src/middleware.coffee:49:13
    at process._tickCallback (internal/process/next_tick.js:150:11)`

**Comment by gyoza** [comment]
OK I'll  look at my npm installation later and let you know what I find.

**Comment by gyoza** [comment]
So im using npm.. 3.10.10 lol, and node 6.12.2.. haha pretty old i guess..

**Comment by gyoza** [comment]
It doesnt like this,  msg.http({timeout: 30000}, 'https://api.iextrading.com/1.0/stock/'+ticker+'/quote')

you might take out the timeout: bit as it looks like that has changed in the latest docs,.. I am not a node or javascript pro by anymeans.. 

```
msg.http('https://api.iextrading.com/1.0/stock/'+ticker+'/quote')

```

Might do it for you

**Comment by snazzybunny** [comment]
It worked! Thank you sir. I will get back to you on the ticker API - gonna ask my brother about that one.

**Comment by gyoza** [comment]
< borat >
very naice!
< / borat >
